[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_blog = "7AsEAzLnD54sggAimpqqqyyuyW7WGaSQXzszvKLgVBJx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/satyam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
